spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: game-service-route
          uri: lb://games-service
          predicates:
            - Path=/games/**
        - id: game-library-service-route
          uri: lb://games-library-service
          predicates:
            - Path=/library/**
server:
  port: 8080

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      deffaultZone: http://localhost:8761/eureka
  instance:
    preferIdAddress: true


